### ISSUE TITLE
Add `eslint-plugin-jsonc` plugin

### ISSUE THREAD

**Issue by daanvosdewael** [zeebats/eslint-config#47]
Add the [`eslint-plugin-jsonc`](https://github.com/ota-meshi/eslint-plugin-jsonc) plugin to sort JSON files. One exception is going to be made for `package.json` files, as we use [`sort-package-json`](https://github.com/keithamus/sort-package-json) for that.

**Comment by jochemkeller** [comment]
@daanvosdewael can you review the linked pull request? Thanks!

**Comment by daanvosdewael** [comment]
![](https://media.giphy.com/media/gQTkKvnQy1lEA/giphy.gif)
